name: access_control
description: A new Flutter project.

publish_to: 'none'

version: 1.0.38+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Architecture
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  get_it: ^7.2.0

  #Ui
  cached_network_image: ^3.2.0
  fluttertoast: ^8.0.9
  rounded_loading_button: ^2.1.0
  flutter_screenutil: ^5.5.3+2
  easy_localization: ^3.0.0
  easy_localization_loader: ^1.0.0
  flutter_switch: ^0.3.2
  image_picker: ^0.8.5+3
  flutter_svg: ^1.0.3
  pdf: ^3.8.0
  file_saver: ^0.1.0
  permission_handler: ^9.2.0
  flutter_webview_plugin: ^0.4.0
  webview_cookie_manager: ^2.0.6

  #Functions
  flutter_secure_storage: ^5.0.2
  simple_connection_checker: ^0.2.1
  device_info_plus: ^4.0.0
  package_info_plus: ^1.4.2

  #Services
  firebase_messaging: ^11.4.4
  firebase_core: ^1.19.1
  retrofit: ^3.0.1+1
  json_annotation: ^4.6.0
  pretty_dio_logger: ^1.1.1
  datadog_flutter_plugin: ^1.0.0-beta.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.11
  json_serializable: ^6.3.1

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/languages/


  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
